const loveYouList = [
  "Wǒ ài nǐ",
  "te quiero",
  "I love you",
  "main tumse pyar karta hoon",
  "ahabak",
  "eu te amo",
  "Āmi tōmāẏa bhālōbāsi",
  "ya lyublyu tebya",
  "watashi wa, anata o aishiteimasu",
  "maiṁ tuhānū pi’āra karadā hāṁ",
  "ich liebe dich",
  "Aku tresna sampeyan",
  "salanghae",
  "je t’aime",
  "seni seviyorum",
  "kocham Cię",
  "ya tebe lyublyu",
  "ik hou van je",
  "Se agapó",
  "jag älskar dig"
];